name: flutter_mobx_dio_boilerplate
description: Flutter Mobx Dio Boilerplate

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.0.1

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.1

  # fonts
  google_fonts: ^2.1.0

  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  flutter_mobx: ^2.0.2
  mobx: ^2.0.4

  # Service locator
  get_it: ^7.1.4
  injectable: ^1.4.1
  provider: ^5.0.0

  # data channel
  data_channel: ^2.0.0+1

  # API fetching
  dio: ^4.0.0
  pretty_dio_logger: ^1.2.0-beta-1

  # Connectivity
  data_connection_checker: #^0.3.4
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master

  # Local cache
  shared_preferences: ^2.0.6

  meta: ^1.7.0

  # Logging
  logger: ^1.0.0

  # Routing
  auto_route: ^3.2.4

  # snackbar
  another_flushbar: #^1.10.23
    git:
      url: https://github.com/ganeshrvel/another-flushbar
      ref: 8b74a6aeec415678e2b751f769f73f82a098ed0b

  flash: ^2.0.1

  after_layout: ^1.1.0

  equatable: ^2.0.0

  # validator
  rules: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: any

  # Linting
  lint: ^1.5.3

  # Build runner
  build_runner: ^2.0.5
  source_gen: ^1.0.5

  # Service locator
  injectable_generator: ^1.4.1

  # MobX
  mobx_codegen: ^2.0.3

  # Routing
  auto_route_generator: ^3.2.3

  # Json
  json_serializable: ^5.0.0
  json_annotation: ^4.1.0

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true
  macos: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #  assets:
  #    - assets/images/
  #    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #    - family: ProductSans
  #      fonts:
  #        - asset: assets/fonts/Product-Sans-Regular.ttf
  #        - asset: assets/fonts/Product-Sans-Italic.ttf
  #          style: italic
  #        - asset: assets/fonts/Product-Sans-Bold.ttf
  #          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
